### ISSUE TITLE
partial ratio issue

### ISSUE THREAD

**Issue by kartheekgurram** [xdrop/fuzzywuzzy#15]
FuzzySearch.partialRatio("ola middle school", "henry county board of education")=29
FuzzySearch.partialRatio("henry county board of education", "ola middle school")=35

Shouldn't they be same?

**Comment by kartheekgurram** [comment]
MatchingBlock[] matchingBlocks = DiffUtils.getMatchingBlocks(s1, s2);

should be MatchingBlock[] matchingBlocks = DiffUtils.getMatchingBlocks(shorter, longer);

**Comment by xdrop** [comment]
Thanks for this!
