### ISSUE TITLE
levenshtein distance issue

### ISSUE THREAD

**Issue by kartheekgurram** [xdrop/fuzzywuzzy#19]
levEditDistance("sf&t co., ltd.","sft",1) = 13 when it is actually 11.

apache commons StringUtils.getLevenshteinDistance gives the correct result.

**Comment by kartheekgurram** [comment]
This is not really a bug. StringUtils levenshtein has replace along with insert and delete.

**Comment by xdrop** [comment]
This is what python-levenshtein uses when calculating the ratio and I wanted to stick to it as much as possible


levEditDistance("sf&t co., ltd.", "sft", 1) will give you 13
levEditDistance("sf&t co., ltd.", "sft", 0) will give you 11 as you expected (After #21)
