### ISSUE TITLE
FuzzySearch.weightedRatio have ExceptionInInitializerError exeption on Android 5 versoin

### ISSUE THREAD

**Issue by ololokiras** [xdrop/fuzzywuzzy#24]
When I try to use FuzzySearch.weightedRatio("lupa","pupa") on Android 5.1, I receive ExceptionInInitializerError. I use FuzzySearch library by Gradle: compile 'me.xdrop:fuzzywuzzy:1.1.5'. Have you any idea?
P.S.: Android v4 do it well on all 4.* versions.

**Comment by xdrop** [comment]
Can you post a stacktrace?

**Comment by ololokiras** [comment]
Here is my function takes a list of addresses
 @Override
    public void ServerReply_CityStreetList(StreetResult result, String searchString) {
        double max_coeff = 0;
        String best_street = null;
        String fuzzyString=null;
        String coefString=null;
        if (result.result.result.equals("OK")) {
            if(result.result.result.length()<1)
                return;
            for (int i = 0; i < result.street.length; i++) {
                double coeff = compareString(result.street[i].street, selected_street);
                if (coeff > max_coeff) {
                    max_coeff = coeff;
                    coefString = result.street[i].street;
                }
            }
            fuzzyString=GetTopSearchLike(result.street,searchString);
            if(fuzzyString==null && coefString==null)
                return;
            if(FuzzySearch.weightedRatio(searchString,fuzzyString)>FuzzySearch.weightedRatio(searchString,coefString))
            {
                best_street=fuzzyString;
            }
            else {
                best_street=coefString;
            }
...............

This my gradle file:
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
    }
}

//apply plugin: 'com.android.library'
apply plugin: 'com.android.application'

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile 'com.google.android.gms:play-services:8.1.0'
    compile 'com.android.support:support-v4:23.1.0'
    compile 'com.android.support:cardview-v7:23.1.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:design:24.0.0'
    compile 'me.xdrop:fuzzywuzzy:1.1.5'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.yandex.android:mobmetricalib:2.51'
    compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
}

configurations {
    // all*.exclude group: 'com.android.support', module: 'support-v4'
}

android {
    defaultConfig.applicationId = "com.iknow72.taxinonstop"
    signingConfigs {
        /*  release {
            storeFile file("/Users/sergeymarkov/Documents/CloneNonStop-Android-Client/nonstop-android-client/keys/nonstop.keystore")
            storePassword "3RcjzdS78B"
            keyAlias "alias_name"
            keyPassword "3RcjzdS78B"
        }*/
    }

    compileSdkVersion 23
    buildToolsVersion '23.0.2'
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 37
        versionName "3.0.4"
        multiDexEnabled true
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }
    allprojects {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
        }
        repositories {
            jcenter()
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // Move the tests to tests/java, tests/res, etc...
        instrumentTest.setRoot('tests')

        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
}

This my GetTopSearchLike function. Have FuzzySearch.ratio() and do it well.
public static String GetTopSearchLike(TaxiNonStopServerAPI.StreetName[] answer, String search) {
		HashMap<String,Integer> streerWithRatio=new HashMap<String, Integer>();
		for(TaxiNonStopServerAPI.StreetName street:answer){
			streerWithRatio.put(street.getName(), FuzzySearch.ratio(search,street.getName()));
		}
		streerWithRatio=(HashMap<String,Integer>)sortByValue(streerWithRatio);

		ArrayList<String> sortByFuzzyString=new ArrayList<String>();
		for(String street:streerWithRatio.keySet()){
			sortByFuzzyString.add(street.toString());
		}
		Collections.reverse(sortByFuzzyString);
		if(sortByFuzzyString.size()>0)
			return sortByFuzzyString.get(0);
		else
			return null;
	}

**Comment by vipulpurohit** [comment]
Happening with me too.
Even with _tokenSetRatio_ _tokenSetPartialRatio_ _tokenSortPartialRatio_ and _tokenSortRatio_.
I think it's happening if there is any special character in string like: (  ) or /

**Comment by xdrop** [comment]
From your stacktrace it seems that the flag `Pattern.UNICODE_CHARACTER_CLASS` is not supported even though it's part of standard [Java 7 ](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#UNICODE_CHARACTER_CLASS)

People are also experiencing it [here](https://github.com/atlassian/commonmark-java/issues/71) as it seems. I'll try to look into this and worst case I'll add an Android specific workaround .

**Comment by xdrop** [comment]
@ololokiras I don't have the tools needed to test this but can you try this [[Download](https://github.com/xdrop/fuzzywuzzy/releases/tag/fix)]

**Note:** Delete the dependency from gradle, and add the **jar** as a library

**Comment by ololokiras** [comment]
@xdrop Thank you for direct link to jar. I  thought about this way.
@vipulpurohit I test get length without special character, and try test with eazy words `FuzzySearch.weightedRatio("lupa","pupa")`, but result was with same error.

**Comment by xdrop** [comment]
@ololokiras Does the link resolve your issue?

**Comment by vipulpurohit** [comment]
@xdrop I have tested it you build with fix. It's working for me with _weightedRatio_.

**Comment by xdrop** [comment]
I've published this, hopefully it resolves the issue.
