### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by vellrya** [xdrop/fuzzywuzzy#33]
Hi. Ratio value between words "гигантская" and "гигансткая" is 90.
In my opinion, here something is wrong. Or is this a normal result of the library?

**Comment by vellrya** [comment]
![image](https://cloud.githubusercontent.com/assets/13716114/24520129/0a0b32de-1590-11e7-85a4-4e4d4fc148a4.png)

**Comment by xdrop** [comment]
@vellrya That's strange.

I just ran:
`        System.out.println(FuzzySearch.ratio("гигантская","гигантская"));
`
And it prints `100`

**Comment by vellrya** [comment]
Haha) Look at this letters: "гиганТСкая" and "гиганСТкая." The change of two letters between them reduces the ratio by 10 points. 
That's exactly what I wanted to pay attention to

**Comment by xdrop** [comment]
@vellrya Hahah well done spotting that 😄 

Closing this then as it was a typo
