### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by cgivre** [xdrop/fuzzywuzzy#35]
Hello and thank you for publishing this awesome library!  I had a question for you regarding the licensing.  I wrote a collection of UDFs for Apache Drill that essentially is a wrapper for your library and would like to submit it to Drill, however the GPL license is not compatible with the Apache license. 
Would you consider re-releasing this under a different license so that it could be included in a future release of Drill?  (https://www.apache.org/legal/resolved.html#category-x) 
Thanks!
-- Charles

**Comment by xdrop** [comment]
Unfortunately this is a rewrite of https://github.com/seatgeek/fuzzywuzzy, which forces this to be licensed under GPL as the original library:

> The "Program", below, refers to any such program or work, and a "work based on the Program" means either the Program or any derivative work under copyright law: that is to say, a work containing the Program or a portion of it, either verbatim or with modifications **and/or translated into another language**.

You could try asking there and if you get permission I would happily release it with a different license.
