### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by GaneshShetty951** [xdrop/fuzzywuzzy#37]
Thank you for this awesome library,  using it for my android project. it taking a lot of time as I am inputting array list of strings for comparison for each time user enters new character it will be called.
is there anyway I can improve its performance....

**Comment by xdrop** [comment]
@GaneshShetty951 Can you share some code on how this is being used?

**Comment by GaneshShetty951** [comment]
`if (BuildConfig.DEBUG_MODE)
                Log.i("***********************", "*********************************************");

            prodlist.addAll(FuzzySearch.extractTop(key, productNameList, 4));

            /***************** Category Name Listing *******************/

            if (BuildConfig.DEBUG_MODE)
                Log.i("***********************", "*********************************************");

            catlist = FuzzySearch.extractTop(key, categoryNameList, 2);
            catlist.addAll(prodlist);
            Collections.sort(catlist, new CustomComparator());
            for (ExtractedResult e : catlist) {
                if (BuildConfig.DEBUG_MODE)
                    Log.i(e.getString(), " " + e.getScore());
            }`

**Comment by xdrop** [comment]
@GaneshShetty951 I can't manage to reproduce this. Is your string list extremely large? How often is this piece of code called?

**Comment by magneticflux-** [comment]
@GaneshShetty951 You should have a look at how [davideas/FlexibleAdapter](https://github.com/davideas/FlexibleAdapter) has implemented filtering of RecyclerViews. There are two improvements:
1. Filtering is asynchronous, so the main UI thread is not affected
2. Filtering waits for a configurable amount of time (usually around 200ms) before executing, letting users delay filtering until they are finished typing by typing reasonably quickly.

**Comment by searchy2** [comment]
@magneticflux- I'm using FlexibleAdapter with FuzzyWuzzy in my notes app and it works so smoothly. One of the proudest feature of my app.

You can see my implementation here: https://github.com/searchy2/Rocket-Notes/blob/master/app/src/main/java/stream/rocketnotes/MainActivity.java

**Comment by GaneshShetty951** [comment]
@xdrop most of time array list size will be more than 1000

**Comment by GaneshShetty951** [comment]
@magneticflux @searchy2  Thank you guys. I will look into that.
