### ISSUE TITLE
partialRatio issue

### ISSUE THREAD

**Issue by overwerk** [xdrop/fuzzywuzzy#39]
FuzzySearch.partialRatio("kaution", "kdeffxxxiban:de1110010060046666666datum:16.11.17zeit:01:12uft0000899999tan076601testd.-20-maisonette-z4-jobas-hagkautionauszug");

Result is "57", I expect "100". 

Using 1.1.9.

**Comment by xdrop** [comment]
Related:
https://github.com/seatgeek/fuzzywuzzy/issues/79
https://github.com/ztane/python-Levenshtein/issues/16

**Comment by BobLd** [comment]
Problem apparently comes from ` DiffUtils.editOpsFromCostMatrix()`: The if statement from line 159 https://github.com/xdrop/fuzzywuzzy/blob/47832295b41aa4e5f77445fbf7149c0e500a9d09/diffutils/src/me/xdrop/diffutils/DiffUtils.java#L159 should be moved to be the first if statement (moved to line 130) https://github.com/xdrop/fuzzywuzzy/blob/47832295b41aa4e5f77445fbf7149c0e500a9d09/diffutils/src/me/xdrop/diffutils/DiffUtils.java#L130

**Comment by xdrop** [comment]
1.3.0 now in staging. Will be available soon.
