### ISSUE TITLE
fuzzywuzzy search gives 86% for all mismatches, or for incorrect match

### ISSUE THREAD

**Issue by gs005** [xdrop/fuzzywuzzy#77]
Thanks for creating this Java API. it is really useful.

But i am facing one issue, I need to match some addresses in big address list (6000+ records). I am using ExtractOne method.

It works perfect if similar address is in the List. It give correct score (87%-100%). 

But if it doesn't find good match, it always gives me 86% match even both addresses are totally different.
 Example - 
Addr 1 - HUNTINGTON NATIONAL   BANK 328 SOUTH SAGINAW ST  FLINT MI   48502 
It matches to  - BANK OF WEST PO BOX 2000  OMAHA NE 68103 
and give Score - 86%

**Comment by gs005** [comment]
@xdrop , can you tell me, is there any configuration or some thing to fix the score where i always get 86% for all the mismatches?

**Comment by xdrop** [comment]
It seems the TokenSet is misbehaving with this one. Please use one of the others (eg. PartialRatio)

```
FuzzySearch.extractOne(query, list, new PartialRatio())
```

**Comment by gs005** [comment]
@xdrop thanks a lot xdrop, it worked perfectly :)
