### ISSUE TITLE
GPL - v2 or v3?

### ISSUE THREAD

**Issue by ajorg-aws** [xdrop/fuzzywuzzy#78]
Hello,

In #35 you've noted that "this is a rewrite of https://github.com/seatgeek/fuzzywuzzy, which forces this to be licensed under the same license (GPL) as the original library."

The Python package is [licensed under GPL-2.0](https://github.com/seatgeek/fuzzywuzzy/commit/d079d6b8ed60f239756e15b9283009f1d442783a) without clarification if it's GPL-2.0-or-later or GPL-2.0-only, and some implication in the commit message and the timing of when the Python project was relicensed from MIT to GPL-2.0 that it was probably meant to be GPL-2.0-only.

This port has [a GPL-3.0 license file](https://github.com/xdrop/fuzzywuzzy/commit/1b0ecfb0982ba03bcdef94961d53a982050f2858).

Was it your intention to license this project under GPL-2.0 to match the license of the original project? If so, would you have any objection to taking the GPL-2.0 license text instead of GPL-3.0?

Thanks!

**Comment by burdoto** [comment]
The license must match the project it comes from - so it should be v2.

**Comment by xdrop** [comment]
> The license must match the project it comes from - so it should be v2.

Not necessarily.

> This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

That being said, I have no objection in switching to GPL version 2. I'll update this soon.

**Comment by xdrop** [comment]
Done

**Comment by ajorg-aws** [comment]
Thank you!

**Comment by ajorg-aws** [comment]
Hello. A colleague noticed that there's still a [`header.txt`](https://github.com/xdrop/fuzzywuzzy/blob/master/header.txt) that references GPLv3. Can that be removed, or replaced with GPLv2 header text to make licensing more clear?

**Comment by xdrop** [comment]
> Hello. A colleague noticed that there's still a [`header.txt`](https://github.com/xdrop/fuzzywuzzy/blob/master/header.txt) that references GPLv3. Can that be removed, or replaced with GPLv2 header text to make licensing more clear?

I've updated it.

**Comment by ajorg-aws** [comment]
Thanks!
