### ISSUE TITLE
v1.3.0 I can't find the .pom file

### ISSUE THREAD

**Issue by AmiraDowidar** [xdrop/fuzzywuzzy#81]
Hello,
I'm trying to use v 1.3.0 but I'm facing the following error

> Could not find me.xdrop:fuzzywuzzy:1.3.0.
> Searched in the following locations:
>   - https://repo.maven.apache.org/maven2/me/xdrop/fuzzywuzzy/1.3.0/fuzzywuzzy-1.3.0.pom
>   - https://jcenter.bintray.com/me/xdrop/fuzzywuzzy/1.3.0/fuzzywuzzy-1.3.0.pom
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

I can't find the .pom file in the following directories
https://repo.jfrog.org/artifactory/libs-release-bintray/me/xdrop/fuzzywuzzy/1.3.0/
https://repo.maven.apache.org/maven2/me/xdrop/fuzzywuzzy/1.3.0/

am I missing something?
I have the following repositories defined in my build.gradle
```
repositories {
  jcenter()
  mavenCentral()
}
```

**Comment by burdoto** [comment]
Could you please provide your complete dependency declaration from gradle?

**Comment by AmiraDowidar** [comment]
Here's my dependencies

```
dependencies {
    implementation "joda-time:joda-time:2.10.5"
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'me.xdrop:fuzzywuzzy:1.3.0'
}
```

**Comment by burdoto** [comment]
the latest available version on maven central seems to be `1.2.0`

this is a mistake and i'm sure @xdrop will take care of this asap

meanwhile, you could try depending on a version that you published to your mavenLocal() repository from a clone, but this is just an idea :)

**Comment by xdrop** [comment]
Hmm, looks like it didn't sync to maven central fully. Taking a look

**Comment by AmiraDowidar** [comment]
I already did that :)
I wanted to be sure that I'm not misconfiguring anything in my build.gradle file

Thank you so much.

**Comment by xdrop** [comment]
I've just triggered another sync. It will take a while to update but if it's not there by tomorrow I might have to either republish or push to a new version

**Comment by AmiraDowidar** [comment]
@burdoto @xdrop Thank you both so much.
I will check again tomorrow.

**Comment by xdrop** [comment]
I couldn't get 1.3.0 to be refreshed (even after deleting and republishing), so I'm pushing 1.3.1 out. Will check again once its synced

**Comment by xdrop** [comment]
1.3.1 should be out now. @AmiraDowidar can you confirm whether it works?

**Comment by AmiraDowidar** [comment]
Yes, I can confirm v 1.3.1 is working correctly.
Thanks.
