### ISSUE TITLE
Difference in extractOne results compared to Python version

### ISSUE THREAD

**Issue by amerfarooq** [xdrop/fuzzywuzzy#82]
I just noticed a difference in the results of extractOne between the Python and Java version. 
My token is `19 craven park harlesden` and my choices are `["NW10 8SU", "19 Craven Park, Harlesden", "Steven Gerrard"]`.

In the Python version, the following code:

```python
process.extractOne(query, choices, scorer=fuzz.ratio)
```
produces:

`('19 Craven Park, Harlesden', 98)`

In the Java version, the following code:

```java
 ExtractedResult result = FuzzySearch.extractOne(query, choices, new SimpleRatio());
```
matches `19 Craven Park, Harlesden` but with a score of `86` score instead.

I dug a bit deeper into this and found that you can get `86` but doing a direct ratio comparison in the Python version:

`fuzz.ratio("19 Craven Park, Harlesden", "19 craven park harlesden")` gives `86`

However, in the `extractOne` function in Python, it first processes the string by calling `full_process` in `utils.py` before calling the ratio function. From the results of the Java version, it seems this it is not processing the string in the same way before calling `SimpleRatio()`. 

It's either this or I am making some mistake in calling the function. Could you please shed some light on this.

**Comment by xdrop** [comment]
You can try:

`BoundExtractedResult<String> result = FuzzySearch.extractOne(query, choices, new DefaultStringFunction(), new SimpleRatio());`

If not 100% the same then you can write your own string function to process in a similar way

**Comment by amerfarooq** [comment]
Thank you for clarifying. I have elected to use my own function as I needed to do things in a slightly different way but this does give similar results to the Python version.
