### ISSUE TITLE
Convert codes to apex class

### ISSUE THREAD

**Issue by munawirrahman** [xdrop/fuzzywuzzy#89]
Hi,

I want to convert your fuzzywuzzy codes to apex class language (language in Salesforce cloud), which has very similar syntax to Java. But currently I'm only planning to use SimpleRatio and PartialRatio. Am I allowed to do that? I also plan to opensource the result to my own project

Thank you in advance!

**Comment by xdrop** [comment]
>Hi,
>I want to convert your fuzzywuzzy codes to apex class language (language in Salesforce cloud), which has very similar syntax to Java. But currently I'm only planning to use SimpleRatio and PartialRatio. Am I allowed to do that? I also plan to opensource the result to my own project


Absolutely you are free to do so, as long as you comply with the [LICENSE](https://github.com/xdrop/fuzzywuzzy/blob/master/LICENSE) rules (which at the time of writing this is GPL 2.0).

The license does apply to:
>"work containing the Program or a portion of it, either verbatim or with modifications and/or translated into another language"

I would recommend reading it, and the restrictions it implies, that should give you a good idea of what you can/cannot/must do. A friendlier version is available [here](https://tldrlegal.com/license/gnu-general-public-license-v2). If you want to use this in a commercial setting and you are uncertain about the implications of GPL 2.0 I would advice talking to your legal department 🙂

**Comment by munawirrahman** [comment]
Hi xdrop, thanks for the insight. I'll let u know when I finish with the project and credits you as well

**Comment by munawirrahman** [comment]
Hi xdrop, I finished to port the basic functions (SimpleRatio and PartialRatio) you can see the docs here: https://munawirrahman.medium.com/fuzzywuzzy-algorithm-with-salesforce-flow-39e4b2ad1918

Also, I found it its hard to test FuzzyWuzzy functions in internet without having to install the library, so I also created the UI for people, to actually test FuzzyWuzzy here: https://mooon-developer-edition.ap16.force.com/s/

thank you

**Comment by xdrop** [comment]
> Hi xdrop, I finished to port the basic functions (SimpleRatio and PartialRatio) you can see the docs here: https://munawirrahman.medium.com/fuzzywuzzy-algorithm-with-salesforce-flow-39e4b2ad1918
> 
> Also, I found it its hard to test FuzzyWuzzy functions in internet without having to install the library, so I also created the UI for people, to actually test FuzzyWuzzy here: https://mooon-developer-edition.ap16.force.com/s/
> 
> thank you

Nice, well done!
