### ISSUE TITLE
Using custom object Instead of String would lead to performance issue?

### ISSUE THREAD

**Issue by Zaky7** [xdrop/fuzzywuzzy#92]
Hi, First of all, thanks @xdrop for work on this project. 

I have a **Spring boot Webflux** project and I need to do a fuzzy search on one of the fields. I am using **in-memory** loading, as soon as my Application starts, I would load the fuzzy search list data in the respective list. On subsequent API calls

After reading the API docs, I have two approaches in my mind.

#### 1. Approach first

Use the list of string keys in a variable and a map of keys to the equivalent object in another variable. Fuzzy search using the list of keys. When I get the response back, map the key to the object and return

```kotlin
data class WeatherData(val key: String, val region: String)

// Service function for getting fuzzy search extracted Result
@Component
class FuzzySearchClient(val keys: MutableList<String>, val keysToWeatherDataMap: MutableMap<String, WeatherData> = mutableMapOf()) {

    fun fuzzySearchInMemory(query: String): Mono<List<SearchResponse>> {
        val result: List<ExtractedResult> = FuzzySearch.extractTop(query, keys, 5)
        val searchList: List<SearchResponse> = result.map { extractedResult: ExtractedResult ->
            val WeatherData = keysToWeatherDataMap[extractedResult.string]
            SearchResponse(WeatherData?.key!!, WeatherData.region!!)
        }
        return Mono.just(searchList)
    }
}
```

Function for adding keys in memory  takes **~6s** with approach one

```kotlin
@Component
class LoadDataInMemoryCache(
    private val weatherDataRepository: WeatherDataRepository,
    private val searchClient: FuzzySearchClient
) {

    private val logger = KotlinLogging.logger {}


    @EventListener(ApplicationReadyEvent::class)
    fun loadData() {
        val startTime = AtomicReference<Long>()
        weatherDataRepository.findAll()
            .doOnSubscribe { startTime.set(System.nanoTime()) }
            .doFinally { logger.info("Time taken for adding data in memory ${TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startTime.get())} milliseconds.") }
            .subscribe {
                searchClient.keys.add(WeatherData(it?.key!!, it.region!!))
            }
    }
}
```

#### 2. Approach two
Use weather object keys and define ToStringFunction and get the result and map to the appropriate response. 

```kotlin
data class WeatherData(val key: String, val region: String)

data class SearchResponse(val key: String, val region: String)

class WeatherSearchToStringFunction: ToStringFunction<WeatherData> {
    override fun apply(item: WeatherData?): String {
        return item?.key!!
    }
}


@Component
class SearchClient(val keys: MutableList<WeatherData>) {
    fun fuzzySearchInMemory(query: String): Mono<List<SearchResponse>> {
        val result: MutableList<BoundExtractedResult<WeatherData>> = FuzzySearch.extractTop(query, keys, WeatherSearchToStringFunction(), 5)
        val searchList: List<SearchResponse> = result.map { extractedResult: BoundExtractedResult<WeatherData> ->
            SearchResponse(extractedResult.referent?.key!!, extractedResult.referent.region)
        }
        return Mono.just(searchList)
    }
}
```

I am not sure which approach to perform. Suggestions are welcomed.

**Comment by burdoto** [comment]
Personally, I would suggest using the second approach, as the toString conversion is done initially inside FuzzyWuzzy and should not have a major performance impact.

**Comment by Zaky7** [comment]
After going deep in the library I understood how ToStringFunction is used. 

I prefer to use the second approach as it saves me build a map of key and its object representation.
When I found the result, I need not map the `ExtractedResult.string` to its actual object, in order to return other params of the object. 

I think we can close this issue

Thanks @burdoto
