### ISSUE TITLE
How to set the scorer like the python fuzzywuzzy?

### ISSUE THREAD

**Issue by Zaky7** [xdrop/fuzzywuzzy#93]
In the python fuzzy-wuzzy, we can set the scorer we want to use in extracting the result. How we can do it here?

```python
process.extractOne("System of a down - Hypnotize - Heroin", songs, scorer=fuzz.token_sort_ratio)
    ("/music/library/good/System of a Down/2005 - Hypnotize/10 - She's Like Heroin.mp3", 61)

```
Do we have any gitter, discord in order to ask such questions?

**Comment by burdoto** [comment]
FuzzyWuzzy features the Ratios as [standalone classes](https://github.com/xdrop/fuzzywuzzy/tree/master/src/me/xdrop/fuzzywuzzy/ratios), and a [set of classes for algorithms](https://github.com/xdrop/fuzzywuzzy/tree/master/src/me/xdrop/fuzzywuzzy/algorithms).

I think https://github.com/xdrop/fuzzywuzzy/blob/master/src/me/xdrop/fuzzywuzzy/algorithms/TokenSort.java is the one that you are looking for.

**Comment by Zaky7** [comment]
@burdoto I am in a situation where the fuzzy match is not giving me acceptable results

```kotlin
 val query = "Berry"
    val searchKeys = listOf("B", "ARRY", "AGEN", "Abercrombie & Fitch Company", "BlackBerry Limited")
    val result = FuzzySearch.extractTop(query, searchKeys, 5)
    result.forEach { extractedResult: ExtractedResult ->
        println(extractedResult)
    }
```

Output

```java
(string: B, score: 90, index: 0)
(string: BlackBerry Limited, score: 90, index: 4)
(string: Abercrombie & Fitch Company, score: 72, index: 3)
(string: ARRY, score: 67, index: 1)
(string: AGEN, score: 22, index: 2)
```


I don't know why B has a score of 90. I need to dig deeper, If you have suggestions regarding this, they are welcome

Currently I am thing of tweaking the score to get results

**Comment by burdoto** [comment]
Honestly, `B` scoring as much as `BlackBerry` for the string `Berry` seems very reasonable to me.

Each `Ratio` and `Algorithm` also implements `Applicable`, so you should try using the `Extractor` class directly and passing an instance of the `TokenSort` algorithm, like this:
```java
var extractor = new Extractor();
Object bestMatch = extractor.extractOne("Berry", values, new TokenSort());
```

**Comment by Zaky7** [comment]
Thanks main :)

**Comment by Zaky7** [comment]
@burdoto can you comment on how much this library is similar to Python Fuzzywuzzy. I have a lot of scorer on fuzzy wuzzy side.

**Comment by burdoto** [comment]
As far as I know, this is an as-perfect-as-it-gets source port of the library. It even features bugs that are inside the original! 🥳

**Comment by burdoto** [comment]
If the issue is now resolved; could you please mark this issue as resolved, too?
