### ISSUE TITLE
Still Incompatibility with the Python Version

### ISSUE THREAD

**Issue by DoronRippel** [xdrop/fuzzywuzzy#98]
I saw that there was a new version 1.3.4, so I used it, but I think that underscore-handling issue is not fixed - all the examples now return 100...

**Here is how I run them in Java:**
_System.out.println("expected 58 -> got " + FuzzySearch.tokenSetPartialRatio("worm_mikeala", "mikeala rath"));
System.out.println("expected 80 -> got " + FuzzySearch.tokenSetPartialRatio("c_wasyluka", "crystal wasyluka"));
System.out.println( "expected 78 -> got " + FuzzySearch.tokenSetPartialRatio("a_bacdefg", "crystal bacdefg"));_

I get:
expected 58 -> got 100
expected 80 -> got 100
expected 78 -> got 100

**and here is how I run them in Python:**
_from fuzzywuzzy import fuzz
if __name__ == '__main__':
    print(fuzz.partial_token_set_ratio("worm_mikeala", "mikeala rath"))
    print(fuzz.partial_token_set_ratio("c_wasyluka", "crystal wasyluka"))
    print(fuzz.partial_token_set_ratio("a_bacdefg", "crystal bacdefg"))_

I get:
58
80
78

Am I doing something wrong or is there still an issue?

**Comment by xdrop** [comment]
Can you try:
```
FuzzySearch.tokenSetPartialRatio("worm_mikeala", "mikeala rath", ToStringFunction.NO_PROCESS)
```

There seems to be some inconsistency in the way the strings are preprocessed, I'll look into it further

**Comment by DoronRippel** [comment]
Thank you.
Running with the *ToStringFunction.NO_PROCESS* flag returned 2 correct
results out of 3 tests:

> For comparison of 'worm_mikeala' and 'mikeala rath': expected 58 -> got 74
> For comparison of 'c_wasyluka' and 'crystal wasyluka': expected 80 -> got
> 80
> For comparison of 'a_bacdefg' and 'crystal bacdefg': expected 78 -> got 78
>

**Comment by xdrop** [comment]
Thanks, have pushed another fix. Give 1.4.0 another go (no need for NO_PROCESS) and let me know if it's not fixed

**Comment by DoronRippel** [comment]
Works now properly!
Thank you
